# сборка в режиме development

# базовый образ:
FROM node:24.13-alpine

# рабочая директория внутри контейнера:
WORKDIR /app

# копируем package.json и package-lock.json (для кэширования npm install):
COPY package*.json ./

# устанавливаем все зависимости (dependencies и devDependencies):
RUN npm install

# копируем исходники:
COPY index.js ./
COPY public/ ./public/
COPY src/ ./src/

# скрипт запуска из package.json:
CMD ["npm", "run", "dev"]
